### ISSUE TITLE
PYTHONPATH hardcoded to src/main/python

### ISSUE THREAD

**Issue by polopi** [alex-dow/pybuilder_nose#3]
Hello and thanks for the plugin.

Unfortunately, I can't make it work on my project, since I'm not using the standard directory structure (legacy).
Since the PYTHONPATH is hardcoded, I can't override it via a property.
I think it is better to let that to the user.

**Comment by alex-dow** [comment]
As you may no doubt have figured out by now, this project is dead.

I neither use nose nor pybuilder anymore.
