### ISSUE TITLE
Unable to override "nose_" args

### ISSUE THREAD

**Issue by eddgrant** [alex-dow/pybuilder_nose#5]
Hi,

I have a simple project which tries to override a nose arg as per the readme:

    @init
    def initialize(project):
        project.set_property('nose_cover-xml-file', "/some/path")

However this seems to be ineffective when the task comes to run. Having had a quick look at the code I think it might be because this plugin is setting the properties within the `@task` rather than within the `init()` method?

https://github.com/alex-dow/pybuilder_nose/blob/2c324210b4f69c494de9e14564b5f4ed6ce48a0f/src/main/python/pybuilder_nose/tasks.py#L33

If you think this is an accurate assessment of the issue, would you be open to a PR to fix it?

Thanks for creating the plugin btw!

Cheers,

Edd

**Comment by alex-dow** [comment]
As you may no doubt have figured out by now, this project is dead.

I neither use nose nor pybuilder anymore, sorry :/
